# Generated by Django 4.2 on 2024-06-28 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0002_alter_departamento_shor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=50, verbose_name='habilidad')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('full_name', models.CharField(blank=True, max_length=120, verbose_name='Nombre Completos')),
                ('job', models.CharField(choices=[('0', 'contandor'), ('1', 'administrador'), ('2', 'economista'), ('3', 'otro')], max_length=1, verbose_name='Trabajo')),
                ('avatar', models.ImageField(null=True, upload_to='empleado')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento')),
                ('habilidades', models.ManyToManyField(to='empleados.habilidades')),
            ],
        ),
    ]
