# Generated by Django 4.2 on 2025-01-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(max_length=50, verbose_name='Trabajo'),
        ),
    ]
