# Generated by Django 4.2 on 2025-07-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_empleado_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_contratacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de contratación'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario'),
        ),
    ]
