# Generated by Django 4.2 on 2024-05-20 01:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_empleado_hoja_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fuull_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre Completos'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='hoja_vida',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
