# Generated by Django 4.2 on 2026-07-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_empleado_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='comprobante_domicilio',
            field=models.FileField(blank=True, null=True, upload_to='documentos/comprobantes'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto de emergencia'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='contrato',
            field=models.FileField(blank=True, null=True, upload_to='documentos/contratos'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='identificacion',
            field=models.FileField(blank=True, null=True, upload_to='documentos/identificaciones'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de emergencia'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='habilidades',
            field=models.ManyToManyField(blank=True, to='empleados.habilidades'),
        ),
        migrations.AlterField(
            model_name='habilidades',
            name='habilidad',
            field=models.CharField(max_length=50, verbose_name='Habilidad'),
        ),
    ]
