# Generated by Django 4.2 on 2024-06-15 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_empleado_fuull_name_alter_empleado_hoja_vida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='fuull_name',
            new_name='full_name',
        ),
    ]
