# Generated by Django 4.2 on 2024-06-15 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_rename_fuull_name_empleado_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='hoja_vida',
            new_name='CV',
        ),
    ]
