# Generated by Django 4.2 on 2024-06-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0009_empleado_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(null=True, upload_to='empleado'),
        ),
    ]
